export const RESERVE_GLOBAL_DETAILS = 'RESERVE_GLOBAL_DETAILS'
export const RESERVE_POL_DETAILS = 'RESERVE_POL_DETAILS'
export const RESERVE_ERROR = 'RESERVE_ERROR'
export const RESERVE_LOADING = 'RESERVE_LOADING'
