export const GET_BASE_P_PIN_TOKEN = "GET_BASE_P_PIN_TOKEN";
export const GET_TOKEN_P_PIN_BASE = "GET_TOKEN_P_PIN_BASE";
export const GET_VALUE_IN_TOKEN = "GET_VALUE_IN_TOKEN";
export const GET_VALUE_IN_BASE = "GET_VALUE_IN_BASE";
export const PRICING_ERROR = "PRICING_ERROR";