export const proposalTypes = [
  {
    value: 'GET_SPARTA',
    label: 'Bond: New Allocation',
    desc: 'Release a Bond Allocation',
    longDesc: '',
    type: 'Action',
    docsLink: 'https://docs.spartanprotocol.org/education/bond',
  },
  {
    value: 'LIST_BOND',
    label: 'Bond: List Asset',
    desc: 'Enable a new bond asset',
    longDesc:
      'Listing an asset for Bond enables it for use in the Bond program. This will allow users to Bond the listed token with protocol-supplied SPARTA to mint LP tokens into the BondVault claimable linearly over 6 months.',
    type: 'Address',
    docsLink: 'https://docs.spartanprotocol.org/education/bond',
  },
  {
    value: 'DELIST_BOND',
    label: 'Bond: Delist Asset',
    desc: 'Disable a bond asset:',
    longDesc:
      'De-listing an asset from Bond disables it for use in the Bond program. Users will no longer be able to Bond the listed token with protocol-supplied SPARTA. Existing Bond positions will still be claimable for the remainder of their bond-period.',
    type: 'Address',
    docsLink: 'https://docs.spartanprotocol.org/education/bond',
  },
  {
    value: 'FLIP_EMISSIONS',
    label: 'Base: Emissions On/Off',
    desc: 'Switch the BASE emissions',
    longDesc: '',
    type: 'Action',
  },
  {
    value: 'REALISE',
    label: 'Pools: Burn synth-premium',
    desc: 'Increase liquidity provider pool-ownership',
    longDesc: '',
    type: 'Address',
  },
  {
    value: 'ADD_CURATED_POOL',
    label: 'Pools: Add Curated',
    desc: 'Add to the curated list',
    longDesc: '',
    type: 'Address',
  },
  {
    value: 'REMOVE_CURATED_POOL',
    label: 'Pools: Remove Curated',
    desc: 'Remove from the curated list',
    longDesc: '',
    type: 'Address',
  },
  {
    value: 'SYNTH_CLAIM',
    label: 'SynthVault: Claim %',
    desc: 'Change SynthVault claim % to',
    longDesc: '',
    units: 'basis points',
    type: 'Param',
  },
  {
    value: 'DAO_CLAIM',
    label: 'DAOVault: Claim %',
    desc: 'Change DaoVault claim % to',
    longDesc: '',
    units: 'basis points',
    type: 'Param',
  },
  {
    value: 'COOL_OFF',
    label: 'DAO: Change Cooloff',
    desc: 'Change DAO CoolOff period to',
    longDesc: '',
    units: 'seconds',
    type: 'Param',
  },
  {
    value: 'GRANT',
    label: 'DAO: Grant SPARTA',
    desc: 'Grant funds to a Spartan',
    longDesc: '',
    units: 'SPARTA',
    type: 'Grant',
  },
  {
    value: 'DAO',
    label: 'DAO: Change Contract',
    desc: 'Change the DAO contract:',
    longDesc: '',
    type: 'Address',
  },
  {
    value: 'ROUTER',
    label: 'Router: Change Contract',
    desc: 'Change Router contract',
    longDesc: '',
    type: 'Address',
  },
  {
    value: 'UTILS',
    label: 'Utils: Change Contract',
    desc: 'Change Utils contract',
    longDesc: '',
    type: 'Address',
  },
  {
    value: 'RESERVE',
    label: 'Reserve: Change Contract',
    desc: 'Change Reserve contract',
    longDesc: '',
    type: 'Address',
  },
]
