export const friends = [
  {
    name: 'Immunefi',
    logo: 'immunefiText',
    desc: 'The leading web3 bug bounty platform, protecting $100 billion in user funds.',
    providing: 'Smart contract bug bounty',
    linkText: ['View Bounty'],
    linkUrl: ['https://www.immunefi.com/bounty/spartanprotocol'],
  },
  {
    name: 'Code4rena',
    logo: 'c4Text',
    desc: 'C4 audit contests find more bugs faster than any other method.',
    providing: '$96k V2 contracts audit contest',
    linkText: ['View Contest'],
    linkUrl: ['https://code423n4.com/reports/2021-07-spartan/'],
  },
  {
    name: 'Certik',
    logo: 'certikText',
    desc: 'Utilizing AI technology to secure & monitor blockchain protocols & smart contracts.',
    providing: 'Traditional audit for original base design',
    linkText: ['View Audit'],
    linkUrl: [
      'https://github.com/spartan-protocol/resources/blob/master/certik-audit.pdf',
    ],
  },
  {
    name: 'CoinMarketCap',
    logo: 'cmcText',
    desc: 'The most-referenced price-tracking website for assets in the cryptocurrency space.',
    providing: 'Spartan Protocol DEX & token listings',
    linkText: ['View Token', 'View DEX'],
    linkUrl: [
      'https://coinmarketcap.com/currencies/spartan-protocol/',
      'https://coinmarketcap.com/exchanges/spartan-protocol/',
    ],
  },
  {
    name: 'Coingecko',
    logo: 'coinGeckoText',
    desc: 'Fundamental analysis of the crypto market including prices, volume & more.',
    providing: 'DEX listing, token listing & DApp pricing data',
    linkText: ['View Token', 'View DEX'],
    linkUrl: [
      'https://www.coingecko.com/en/coins/spartan-protocol-token',
      'https://www.coingecko.com/en/exchanges/spartan_protocol',
    ],
  },
  {
    name: 'GitHub',
    logo: 'githubText',
    desc: 'Build, ship, & maintain software on the largest development platform in the world.',
    providing: 'Open source code hosting & collaboration',
    linkText: ['Dont trust, verify!'],
    linkUrl: ['https://github.com/spartan-protocol/spartanswap-contracts'],
  },
  {
    name: 'Bubblemaps',
    logo: 'bubblemapsText',
    desc: 'Ground-breaking way of exploring on BSC, visually revealing connections between wallets.',
    providing: 'Custom SPARTA Bubblemap analysis tool',
    linkText: ['View Bubblemap'],
    linkUrl: [
      'https://app.bubblemaps.io/bsc/token/0x3910db0600ea925f63c36ddb1351ab6e2c6eb102',
    ],
  },
  {
    name: 'OntoWallet',
    logo: 'ontoText',
    desc: 'Decentralized, cross-chain wallet, for users to securely manage identities, & digital assets.',
    providing: 'SPARTA token & DApp whitelisting',
    linkText: ['ONTO Wallet'],
    linkUrl: ['https://onto.app'],
  },
  {
    name: '4thTech',
    logo: 'fourText',
    desc: 'Send/receive dMails & on-chain messages with no ads, data mining nor tracking.',
    providing: 'Community portal for dMail & dChat',
    linkText: ['View Portal', 'View 4thTech'],
    linkUrl: ['https://spartan.4thtech.io/', 'https://4thtech.io/'],
  },
]
