export const DAOVAULT_LOADING = 'DAO_LOADING'
export const DAOVAULT_ERROR = 'DAO_ERROR'
// DAO FUNCTIONS BELOW
export const GET_DAOVAULT_MEMBER_POOL_WEIGHT = 'GET_DAOVAULT_MEMBER_POOL_WEIGHT'
export const GET_DAOVAULT_TOTAL_WEIGHT = 'GET_DAOVAULT_TOTAL_WEIGHT'
export const GET_DAOVAULT_MEMBER_WEIGHT = 'GET_DAOVAULT_MEMBER_WEIGHT'
