export const DAOVAULT_LOADING = 'DAO_LOADING'
export const DAOVAULT_ERROR = 'DAO_ERROR'
// DAO FUNCTIONS BELOW
export const GLOBAL_DETAILS = 'GLOBAL_DETAILS'
export const MEMBER_DETAILS = 'MEMBER_DETAILS'
